[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solemn = "82H3B7Sf7wEf3nv1u8FTDfgHoRZNzY8poH27RPqcFNCK"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
